version: '3.8'

services:
  db:
    image: postgres:15
    container_name: carplace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: carplace_app
    ports:
      - "5000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/car_api_db
      - SECRET_KEY=${SECRET_KEY:-eyyyyyyy}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
